---
- hosts: newvm
  user: andrew

  vars:
    new_host: yeet
    updates: false
    set_static: false
    static_ip: 192.168.1.161/24
    gateway: 192.168.1.1
    nameservers: [ 192.168.1.5, 1.1.1.1 ]
    reboot: false # note that if true, ansible can't reconnect to the host

  roles:
    - clean_vm
