---
- hosts: newvm
  user: andrew

  #  TODO would be cool to have an option to specify static or dhcp
  vars:
    new_host: unifi
    static_ip: 192.168.1.160/24
    gateway: 192.168.1.1
    nameservers: [ 192.168.1.5, 1.1.1.1 ]

  roles:
    - clean_vm
