---
- hosts: newvm
  user: andrew

  vars:
    new_host: trash1
    set_static: true
    static_ip: 192.168.1.161/24
    gateway: 192.168.1.1
    nameservers: [ 192.168.1.5, 1.1.1.1 ]
    updates: false
    reboot: true # note that if set_static is true this will hang

  roles:
    - clean_vm
