---
- hosts: newvm
  user: andrew

  vars:
    new_host: postgres-1
    static_ip: 192.168.1.209/24

  tasks:
    - include_tasks: tasks/clean.yml
    - include_tasks: tasks/host-name.yml
    - include_tasks: tasks/static-ip.yml

