---
- hosts: k8s-node
  user: andrew

  vars:
    user: andrew
    docker_version: 5:19.03.12~3-0~ubuntu-focal
    k8s_version: 1.18.3-00

  tasks:
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/nfs-client.yml
    - include_tasks: tasks/kubernetes.yml
    - include_tasks: tasks/ip-k8s-node.yml