---
- name: Install required packages for Docker
  apt:
    update_cache: yes
    autoclean: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add Docker's GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repo for 20.04 Ubuntu
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker
  apt:
    update_cache: yes
    autoclean: yes
    name:
      - containerd.io
      - "docker-ce={{ docker_version }}"
      - "docker-ce-cli={{ docker_version }}"

- name: Create a Docker group
  group:
    name: docker
    state: present

- name: Add user to Docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
