---
- name: Download Harbor installer
  get_url:
    url: https://github.com/goharbor/harbor/releases/download/v{{ harbor_version }}/harbor-online-installer-v{{ harbor_version }}.tgz
    dest: /tmp/harbor-{{ harbor_version }}.tar.gz

# TODO
#- name: Verify GPG key
#

- name: Make install directory
  file:
    path: /harbor
    state: directory
    mode: '0777'

- name: Unzip installer
  unarchive:
    remote_src: yes
    src: /tmp/harbor-{{ harbor_version }}.tar.gz
    dest: /harbor

- name: Make cert directory
  file:
    path: /harbor/certs
    state: directory
    mode: '0755'

- name: Generate certs
  script: create-harbor-certs.sh
  args:
    chdir: /harbor/certs

# TODO not sure if should just use scp in the Makefile instead
- name: Copy certs back to host computer
  become: yes
  fetch:
    src: /harbor/certs/ca.crt
    dest: /home/andrew/Github/
    flat: yes

- name: Restart Docker engine
  service:
    name: docker
    state: restarted

#- name: Remove cert directory
#  file:
#    path: /tmp/cert
#    state: absent

- name: Copy Harbor config file
  copy:
    src: ./files/harbor.yml.tmpl
    dest: /harbor/harbor/harbor.yml

- name: Run Harbor installer
  shell: ./install.sh
  args:
    chdir: /harbor/harbor

- name: Copy Harbor systemd service file
  copy:
    src: ./files/harbor.service
    dest: /etc/systemd/system/harbor.service

- name: Enable Harbor service
  systemd:
    name: harbor
    state: started
    enabled: yes
    daemon_reload: yes
