---
- name: Install NFS dependencies
  apt:
    name:
      - nfs-kernel-server
    state: present
    update_cache: yes

# TODO need to set up the disk first:
  # - format mounted disk to ext4 and mount to /export/nfs
  # - add entry to /etc/fstab
  # - change directories to nobody:nogroup and 777

- name: Create exported directories
  file: 'path="{{ item.strip().split()[0] }}" state=directory'
  with_items: "{{ nfs_exports }}"

- name: Create exports file
  template:
    src: ./templates/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644

- name: Export directories
  command: 'exportfs -a'

- name: Ensure NFS nfs-kernel-server is enabled
  service:
    name: nfs-kernel-server
    state: started
    enabled: yes
