---
- name: Clone a template to create a new vm.
  proxmox_kvm:
    node: adi
    api_host: 192.168.1.224
    api_user: root@pam
    api_password: "{{ pxmx_pw }}"
    clone: "{{ clone_name }}"
    vmid: "{{ clone_id }}"
    name: "{{ new_vm_name }}"
    newid: "{{ new_vm_id }}"
    storage: "{{ storage }}"
    format: qcow2
    timeout: 800

- name: Pause for creation
  pause:
    seconds: 15

- name: Start the vm.
  proxmox_kvm:
    node: adi
    api_host: 192.168.1.224
    api_user: root@pam
    api_password: "{{ pxmx_pw }}"
    name: "{{ new_vm_name }}"
    state: started

- name: Pause for boot
  pause:
    seconds: 25
