- name: Disable cloud-init's network configuration capabilities
  copy:
    src: ./files/99-disable-network-config.cfg
    dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg

- name: Assign static IP to eth0
  template:
    src: ./templates/50-cloud-init.j2
    dest: /etc/netplan/50-cloud-init.yaml
  register: eth

# TODO not sure if this from cloud-init or actually a default file
- name: Remove default file in Ubuntu 20.04
  file:
    path: /etc/netplan/00-installer-config.yaml
    state: absent

- name: Apply netplan configuration
  command: netplan apply
  async: 45
  poll: 0
  when: eth is changed

- name: Pause for apply
  pause:
    seconds: 5
