---
- name: Update all system packages
  become: yes
  apt:
    name: "*"
    state: latest
    update_cache: yes

# TODO make this run if specified in playbook
# - name: Reboot time
#   become: yes
#   reboot:
#     reboot_timeout: 600
