- name: Let ens19 use DHCP
  template:
    src: 01-k8s-node.yaml
    dest: /etc/netplan/01-k8s-node.yaml
  register: eth

- name: Apply netplan configuration
  command: netplan apply
  when: eth is changed
