- name: Copy over netplan config
  template:
    src: 00-static-ip.j2
    dest: /etc/netplan/00-static-ip.yaml
  register: eth

- name: Remove default file in Ubuntu 20.04
  file:
    path: /etc/netplan/00-installer-config.yaml
    state: absent

- name: Apply netplan configuration
  command: netplan apply
  async: 45
  poll: 0
  when: eth is changed

- name: Pause for apply
  pause:
    seconds: 5
